### PR TITLE
Resolve issues arising after using aliases

### PR DESCRIPTION
**Pull request by u3u**
My English is very poor, the document translated through Google, Dalao laughed 😅
Unreasonable Place Trouble Dalao fixes 😛
BTW: is Dalao a member of our 196? 😂

### CODE REVIEW

**Comment by egoist** [comment]
why is this PR from a `unknown repository`? I need to tweak it a bit

**Comment by u3u** [comment]
Because I deleted the warehouse after submitting PR, it looks cool! 😂

**Comment by egoist** [comment]
But there's no way to edit it anymore, you should only delete that after PR being merged. I'll update it on my side.

**Comment by u3u** [comment]
Ok, I'll be careful later 😱

**Pull request closed without merging**
